SELECT top 100 * FROM RDL00001_EnterpriseDataWarehouse.dbo.D_Company

SELECT TABLE_NAME,
       TABLE_SCHEMA + '.' + TABLE_NAME AS TABLE_FULL_NAME,
       COLUMN_NAME,
       DATA_TYPE,
       IS_NULLABLE,
       TABLE_CATALOG,
       GetDate() AS Date,
       ORDINAL_POSITION 
FROM [RDL00001_EnterpriseDataStaging].INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME LIKE '%D_Company%' and TABLE_SCHEMA='dbo'
ORDER BY TABLE_NAME, COLUMN_NAME
